version: '3.7'
services:
  currency-exchange:
    image: romanandriiv/spring-cloud-microservices-currency-exchange-service:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network


networks:
  currency-network: